version: "3.4"

services:
  db:
    container_name: trio-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trio
    ports:
      - 6500:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: trio-qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  pgdata: {}
  esdata: {}
  qdrant_data: {}

configs:
  qdrant_config:
    content: |
      log_level: INFO
